name: Github action for ctex-kit test

on: [push]

env:
  TL_PACKAGES: adobemapping amsfonts amsmath atbegshi cjk cjkutils cm ctablestack currfile dvipdfmx epstopdf-pkg etex etoolbox euenc fancyhdr fandol filehook fontspec graphics graphics-cfg graphics-def iftex l3build l3experimental l3kernel l3packages latex-bin lm lm-math ltxcmds lualatex-math lualibs luaotfload luatex luatex85 luatexbase luatexja metafont mfware ms oberdiek platex-tools tex tex-ini-files tools trimspaces ucharcat ulem unicode-data uplatex varwidth xcolor xetex xkeyval xunicode xecjk zhnumber

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install TeX Live
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
        tlmgr install ${{ env.TL_PACKAGES }}
        tlmgr option -- autobackup 0
        tlmgr update --self --all --no-auto-install
        echo $PATH
    - name: Test ctex
      working-directory: ./ctex
      run: |
        export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
        l3build check --quiet --halt-on-error --engine xetex
        l3build check --quiet --halt-on-error --engine luatex

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install TeX Live
      run: |
        export PATH=/tmp/texlive/bin/x86_64-darwin:$PATH
        curl -L -o install-tl-unx.tar.gz http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
        tar -xzf install-tl-unx.tar.gz
        cd install-tl-20* && ./install-tl --profile ../.github/workflows/texlive.profile
        tlmgr install ${{ env.TL_PACKAGES }}
        tlmgr option -- autobackup 0
        tlmgr update --self --all --no-auto-install
        echo $PATH
        ls -al /System/Library/Fonts/
        ls -al /System/Library/Fonts/Supplemental/
        ls -al /Library/Fonts/
    - name: Test ctex
      working-directory: ./ctex
      run: |
        export PATH=/tmp/texlive/bin/x86_64-darwin:$PATH
        l3build check --quiet --halt-on-error --engine xetex
        l3build check --quiet --halt-on-error --engine luatex

  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Run a one-line script
  #     run: echo Hello, world!
  #   - name: Run a multi-line script
  #     run: |
  #       dir
  #       cd
  #       set Path
  #       echo Add other actions to build,
  #       echo test, and deploy your project.
